update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run Unit Tests for the Warcraft SDK"
  lane :unit_test do
     run_tests(workspace: "Warcraft.xcworkspace",
            devices: ["iPhone 12 (14) (14.4)"],
            scheme: "WarcraftTests")
  end

  desc "Build XCFramework"
  lane :build_release do |options|
    build()
    zip_release(options)
  end

  desc "Build XCFramework"
  private_lane :build do
    create_xcframework(
      workspace: 'Warcraft.xcworkspace',
      scheme: 'Warcraft',
      destinations: ['iOS', 'maccatalyst'],
      xcframework_output_directory: 'Artifacts/',
      remove_xcarchives: true,
    )
  end

  desc "Zip Artifacts for Release"
  private_lane :zip_release do |options|
    zip(path: "Artifacts/#{options[:product_name]}.BCSymbolMaps", output_path: "Artifacts/#{options[:product_name]}.BCSymbolMaps.zip")
    zip(path: "Artifacts/#{options[:product_name]}.dSYMs", output_path: "Artifacts/#{options[:product_name]}.dSYMs.zip")
    zip(path: "Artifacts/#{options[:product_name]}.xcframework", output_path: "Artifacts/#{options[:product_name]}.BCSymbolMaps.zip")
  end

end
