update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run Unit Tests for the Warcraft SDK"
  lane :unit_test do
     run_tests(workspace: "Warcraft.xcworkspace",
            devices: ["iPhone 12 (14) (14.4)"],
            scheme: "WarcraftTests")
  end

  desc "List available devices"
  lane :list_devices do
    sh("xcrun simctl list devices")
   end
end
