name: Releases

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.3
          bundler-cache: true

      - name: Extract Version from XCConfig
        run: scripts/sdk_versions.sh

      - name: Build for Release
        run: bundle exec fastlane build_release product_name:Warcraft

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "Artifacts/*.zip"
          bodyFile: "changelog/v0.0.1.md"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.WARCRAFT_VERSION_NUMBER }}
